# Generated by Django 4.2.6 on 2023-11-06 14:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Maximum 5000 characters', max_length=5000, null=True),
        ),
    ]
