# Generated by Django 4.2.6 on 2023-11-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
