# Generated by Django 4.2.6 on 2023-10-31 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_likes_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='blog.post'),
        ),
    ]
