# Generated by Django 4.2.6 on 2023-11-11 16:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_region_left_position_region_top_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image2',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='region',
            name='image3',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
