# Generated by Django 4.2.6 on 2023-10-31 13:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_replies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created'], 'verbose_name': 'Create post', 'verbose_name_plural': 'Create posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Maximum 5000 characters', max_length=5000, null=True),
        ),
    ]
