# Generated by Django 4.2.6 on 2023-11-11 17:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_region_image2_region_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image4',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image4'),
        ),
        migrations.AlterField(
            model_name='region',
            name='image2',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='region',
            name='image3',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image3'),
        ),
    ]
