# Generated by Django 4.2.6 on 2023-11-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_region_left_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('activist', 'Activist'), ('volunteer', 'Volunteer'), ('organization', 'Organization')], default='volunteer', max_length=20),
        ),
    ]
