# Generated by Django 4.2.6 on 2023-11-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
    ]
